# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapskate', '0003_auto_20151025_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=b'copies/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=b'copies/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=b'copies/%Y/%m/'),
        ),
    ]
