# Generated by Django 2.1.1 on 2018-09-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheapskate', '0005_auto_20170122_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ('title',), 'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('checking', 'Checking'), ('cc', 'Credit Card')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ccbill',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheapskate.Account'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='account',
            field=models.ForeignKey(limit_choices_to={'kind': 'cc'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheapskate.Account'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheapskate.ExpenseCategory'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='do_not_project',
            field=models.BooleanField(default=False, verbose_name='One-off Event'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='copies/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(limit_choices_to={'kind': 'checking'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheapskate.Account'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='do_not_project',
            field=models.BooleanField(default=False, verbose_name='One-off Event'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='copies/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account',
            field=models.ForeignKey(limit_choices_to={'kind': 'checking'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheapskate.Account'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='checkno',
            field=models.IntegerField(blank=True, null=True, verbose_name='Check No.'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='do_not_project',
            field=models.BooleanField(default=False, verbose_name='One-off Event'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='copies/%Y/%m/'),
        ),
    ]
