# Generated by Django 2.1.1 on 2018-09-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheapskate', '0006_auto_20180903_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name': 'Income Category', 'verbose_name_plural': 'Income Categories'},
        ),
    ]
