# Generated by Django 2.1.1 on 2018-09-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheapskate', '0007_auto_20180903_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='do_not_project',
            new_name='is_one_off',
        ),
        migrations.RenameField(
            model_name='deposit',
            old_name='do_not_project',
            new_name='is_one_off',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='do_not_project',
            new_name='is_one_off',
        ),
    ]
