# Generated by Django 2.2.3 on 2020-01-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheapskate', '0008_auto_20180903_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
